### ISSUE TITLE
Ability to map selections

### ISSUE THREAD

**Issue by alexherbo2** [occivink/kakoune-sort-selections#1]
I dunno about Perl, but I imagine the command could resemble to something like:

``` kak
map-selections %val{selections} %{
  return(sort($ARGV))
}
```

**Comment by occivink** [comment]
Mh what exactly do you mean by mapping, can you formulate an example of it?

**Comment by alexherbo2** [comment]
The command takes an arg-list as input and uses the return value to map selections.

Here is an example with [Crystal] code:

``` kak
map-selections %reg{.} %{
  ARGV.each_with_index.map do |selection, index|
    "#{index}. #{selection}"
  end
}
```

[Crystal]: https://crystal-lang.org

**Comment by occivink** [comment]
I certainly don't want to expose a programming language in the interface. As a workaround, you could specify the indices in a register and pass that as an argument, would this ok?

**Comment by alexherbo2** [comment]
After a few experiments, I’ve opted for the following approach:

```
pipe <program> [arguments]
```

It takes JSON as input and output.

So for example, to sort selections:

``` kak
pipe jq sort
```

It’s slick with jq, and super verbose with Lua:

``` kak
pipe lua -l json -e %{
  local selections = json.decode(io.read('*a'))

  for index, selection in ipairs(selections) do
    selections[index] = string.format('%d. %s', index, selection)
  end

  io.write(json.encode(selections))
}
```

I was using [json.lua] for testing.

[json.lua]: https://github.com/rxi/json.lua

**Comment by occivink** [comment]
I can see the value in having some programmable interface that is simpler to get right than shell, but it looks to me like your suggestion is about generic selection transformation. This is a much broader scope than I want to handle in this plugin.

**Comment by alexherbo2** [comment]
Yep I was looking for a generic way to not limit to sorting.

I realized with this feature we can easily reimplement some of the built-in commands, like [`rotate_selections_content()`].

[`rotate_selections_content()`]: https://github.com/mawww/kakoune/blob/master/src/normal.cc#:~:text=rotate_selections_content
